[package]
name = "leapfrog"
version = "0.1.0"
edition = "2021"
authors = ["Rob Clucas <robjclucas@gmail.com>"]
license = "MIT OR Apache-2.0"

readme = "README.md"
description = "Fast, lock-free concurrent hash map"
repository = "https://github.com/robclu/leapfrog"

keywords = ["hashmap","concurrent","map"]
categories = ["concurrency", "data-structures"]

[profile.release]
debug = true
lto = true

[dependencies]
atomic = "0.5.1"

[dev-dependencies]
rand = "0.8.4"
core_affinity = "0.5.10"
